#!/usr/bin/env bash

sleep 10

DISPLAY_SECONDARY=$(colormgr find-device-by-property Model "DELL U2312HM" | awk 'BEGIN { FS=": *" } /^Device ID: / { print $2 }')
DISPLAY_PRIMARY=$(colormgr find-device-by-property Model "DELL U2412M" | awk 'BEGIN { FS=": *" } /^Device ID: / { print $2 }')

IMAGE_SCANNER=$(colormgr find-device-by-property Model "FlatbedScanner 22" | awk 'BEGIN { FS=": *" } /^Device ID: / { print $2 }')

colormgr import-profile /private/icc_profiles/dell_u2312hm_standard.icc

PROFILE_DISPLAY_SECONDARY=$(colormgr find-profile-by-filename dell_u2312hm_standard.icc | awk 'BEGIN { FS=": *" } /^Profile ID: / { print $2 }')

colormgr import-profile /private/icc_profiles/dell_u2412m_standard.icc

PROFILE_DISPLAY_PRIMARY=$(colormgr find-profile-by-filename dell_u2412m_standard.icc | awk 'BEGIN { FS=": *" } /^Profile ID: / { print $2 }')

colormgr import-profile /private/icc_profiles/CrScan23.icm

PROFILE_IMAGE_SCANNER=$(colormgr find-profile-by-filename CrScan23.icm | awk 'BEGIN { FS=": *" } /^Profile ID: / { print $2 }')

colormgr device-add-profile "${DISPLAY_SECONDARY}" "${PROFILE_DISPLAY_SECONDARY}"
colormgr device-add-profile "${DISPLAY_PRIMARY}" "${PROFILE_DISPLAY_PRIMARY}"

colormgr device-add-profile "${IMAGE_SCANNER}" "${PROFILE_IMAGE_SCANNER}"
